### ISSUE TITLE
[Bug] edit this page link is broken in online doc

### ISSUE THREAD

**Issue by zxkane** [awslabs/service-workbench-on-aws-cn#54]
**Describe the bug**
`edit this page` link is broken in online doc

**To Reproduce**
1. Go to any online doc page, for example, [this one](https://awslabs.github.io/service-workbench-on-aws-cn/installation_guide/overview)
2. Click the link `Edit this page`
3. the page is 404

**Expected behavior**
Open the source code markdown file of page in github online editor

**Comment by dengmingtong** [comment]
Fixed the issue on PR: https://github.com/awslabs/service-workbench-on-aws-cn/pull/137
