### ISSUE TITLE
[Bug] doc and ui are inconsistent

### ISSUE THREAD

**Issue by zxkane** [awslabs/service-workbench-on-aws-cn#68]
**Describe the bug**
The UI of inviting an AWS account does not match the doc. No vpc, no role arn and so on

<img width="1389" alt="image" src="https://user-images.githubusercontent.com/843303/182806553-30b311d6-9b76-4fde-802e-d8dd9961a325.png">

https://awslabs.github.io/service-workbench-on-aws-cn/user_guide/sidebar/admin/accounts/aws_accounts/invite_member_account

**To Reproduce**

**Expected behavior**

**Screenshots**

**Versions (please complete the following information):**
 - Release Version installed [e.g. v1.0.3]

**Additional context**

**Comment by dengmingtong** [comment]
fixed in [commit](https://github.com/awslabs/service-workbench-on-aws-cn/commit/471898e0ee105f3f9aed06a15d23737a3c4114c8)
