### ISSUE TITLE
[Bug] can not input Chinese characters when creating indexes

### ISSUE THREAD

**Issue by zxkane** [awslabs/service-workbench-on-aws-cn#69]
**Describe the bug**

**To Reproduce**
1. Go to 'Accounts' 
2. Click on 'Indexes'
3. Create new Index, input Chinese characters in the form and click `create` button
4. See error `input validation error`

**Expected behavior**

**Screenshots**

**Versions (please complete the following information):**
 - Release Version installed [e.g. v1.0.3]

**Additional context**

**Comment by dengmingtong** [comment]
Fixed this issue in [PR](https://github.com/awslabs/service-workbench-on-aws-cn/pull/87)
