### ISSUE TITLE
[Bug] highlight incorrect field in screenshot of importing Sagemaker workspace

### ISSUE THREAD

**Issue by zxkane** [awslabs/service-workbench-on-aws-cn#70]
**Describe the bug**

should highlight `instance type` field

![image](https://user-images.githubusercontent.com/843303/182809305-2d25c565-18f8-4da0-ad9e-847c28cc62b0.png)

the field `AutoStopIdleTimeInMinutes` also is required.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Versions (please complete the following information):**
 - Release Version installed [e.g. v1.0.3]

**Additional context**

**Comment by dengmingtong** [comment]
Already fixed
